baseURL: "https://KabirDabholkar.github.io" 
title: Kabir Dabholkar
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        # - name: Books
        #   url: books/
        #   weight: 5 
        - name: Papers
          url: papers/
          weight: 2
        # - name: Courses
        #   url: courses/
        #   weight: 3
        # - name: Data
        #   url: data/
        #   weight: 4 
        # - name: Blog
        #   url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)
        #   weight: 6

params:
    description: "Kabir Dabholkar's website."
    author: Kabir Dabholkar
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["papers"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Kabir Dabholkar
          subtitle: "I am a PhD student at the [**Technion**](https://www.technion.ac.il/en/), in the group of [**Omri Barak**](https://barak.net.technion.ac.il). 
          I study mathematical models of the brain often employing *machine learning*, and *dynamical systems theory*. My research focuses on developing methods to *evaluate*, *compare*, and *reverse-engineer* these models, exploring what they can teach us.
          Previously, I did my undergraduate studies at [**IISER Pune**](https://www.iiserpune.ac.in), where I got my first exposure to computational neuroscience research in the group of [**Suhita Nadkarni**](https://www.iiserpune.ac.in/research/department/biology/people/faculty/regular-faculty/suhita-nadkarni/305).
           "
          imageUrl: "me.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Papers
              url: papers/

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:kabir.dabholkar@students.iiserpune.ac.in
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=UTf-kBAAAAAJ&hl=en
        - name: GitHub
          url: https://github.com/KabirDabholkar
        - name: Bluesky
          url: https://bsky.app/profile/kabirdabholkar.bsky.social

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Kabir Dabholkar"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2